### ISSUE TITLE
TensorRT not found

### ISSUE THREAD

**Issue by AntonioDLC** [argrecsys/arg-min-fm#15]
I have this error when running python3 main.py and can't proceed:

> \>python3 ./src/app/main.py 
> 2024-11-23 19:34:07.542312: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2024-11-23 19:34:08.367428: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> Traceback (most recent call last):
>   File "/home/tuan/Documents/Repos/arg-min-fw/./src/app/main.py", line 12, in <module>
>     from framework.engine import Engine
>   File "/home/tuan/Documents/Repos/arg-min-fw/src/app/framework/engine.py", line 22, in <module>
>     logging.basicConfig(
>   File "/usr/lib/python3.10/logging/__init__.py", line 2040, in basicConfig
>     h = FileHandler(filename, mode,
>   File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
>     StreamHandler.__init__(self, self._open())
>   File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
>     return open_func(self.baseFilename, self.mode,
> FileNotFoundError: [Errno 2] No such file or directory: '/home/tuan/Documents/Repos/arg-min-fw/src/log/engine_log.log'
>

**Comment by Ilnasts** [comment]
I'm having the same issue. Even after purging the dependencies and manually installing some recalcitrant requirements (there were some issues with tensorflow), there seem to be a lot of problems with the code. Even after brute forcing the trials to run by ignoring the engine log error and algos, it still returned errors, firstly relating to the algos. It's a shame, as researchers can't avail themselves of this tool, and credit its creators for it, if they can't use it.

**Comment by ansegura7** [comment]
Hi @AntonioDLC and @Ilnasts,

I’m resuming the maintenance of the project and came across this issue. Are you still experiencing problems running the ArgMining framework?
